In [17]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import normalize

from diff_classifier import features
import diff_predictor
from diff_predictor import data_process

from os import listdir, getcwd, chdir
from os.path import isfile, join

In [2]:
workbookDir = getcwd()
print('Current Notebook Dir: ' + workbookDir)
chdir(workbookDir) # Go to current workbook Dir"
chdir('..')        # Go up one
print(f'Using current directory for loading data: {getcwd()}')
workbookDir = getcwd()

Current Notebook Dir: /Users/nelsschimek/Documents/nancelab/diff_predictor/notebooks
Using current directory for loading data: /Users/nelsschimek/Documents/nancelab/diff_predictor


In [90]:
#third dataset: rotenone
rotenone_data_path = '../diff_predictor/data/MSD_x_y/'
rotenone_msd_filelist = [f for f in listdir(rotenone_data_path) if isfile(join(rotenone_data_path, f)) and 'cort' in f]
print((rotenone_msd_filelist))

['msd_P10F_NT_10DIV_40nm_slice_2_cortex_vid_1.csv', 'msd_P10F_1uM_7DIV_40nm_slice_1_cortex_vid_1.csv', 'msd_P10F_10uM_24h_slice_1_cortex_vid_3.csv', 'msd_P10F_10uM_24h_slice_1_cortex_vid_2.csv', 'msd_P10F_NT_7DIV_40nm_slice_1_cortex_vid_2.csv', 'msd_P10F_5uM_7DIV_40nm_slice_2_cortex_vid_2.csv', 'msd_P10F_NT_10DIV_40nm_slice_2_cortex_vid_2.csv', 'msd_P10F_1uM_7DIV_40nm_slice_1_cortex_vid_2.csv', 'msd_P10F_10uM_24h_slice_1_cortex_vid_1.csv', 'msd_P10F_NT_7DIV_40nm_slice_1_cortex_vid_1.csv', 'msd_P10F_50nM_10DIV_40nm_slice_1_cortex_vid_2.csv', 'msd_P10F_50nM_10DIV_40nm_slice_1_cortex_vid_1.csv', 'msd_P10F_10uM_10DIV_40nm_slice_2_cortex_vid_1.csv', 'msd_P10F_1uM_10DIV_40nm_slice_2_cortex_vid_2.csv', 'msd_P10F_50nM_2h_slice_1_cortex_vid_2.csv', 'msd_P10F_10uM_2h_slice_1_cortex_vid_1.csv', 'msd_P10F_NT_4DIV_40nm_slice_1_cortex_vid_2.csv', 'msd_P10F_50nM_2h_slice_1_cortex_vid_1.csv', 'msd_P10F_NT_4DIV_40nm_slice_1_cortex_vid_1.csv', 'msd_P10F_1uM_10DIV_40nm_slice_1_cortex_vid_2.csv', 'msd_P10

In [89]:
for file in rotenone_msd_filelist:
    df = pd.read_csv(rotenone_data_path + file)
    for traj in df['Track_ID'].unique():
        

497364
415338
2048697
1796109
774690


ParserError: Error tokenizing data. C error: Calling read(nbytes) on source failed. Try engine='python'.

In [88]:
t1 = df[df['Track_ID']==375].dropna()
t2 = df[df['Track_ID']==393][['X', 'Y']]
t2 = t2.dropna()

added = np.add(t1[['X', 'Y']].values, t2[['X', 'Y']].values)

ValueError: operands could not be broadcast together with shapes (126,2) (129,2) 

Unnamed: 0  Frame  Track_ID       X        Y      MSDs     Gauss  \
244125        3255    0.0     375.0  19.908  577.642  0.000000  0.000000   
244126        3256    1.0     375.0  19.539  578.135  0.733938  0.734727   
244127        3257    2.0     375.0  19.710  578.202  1.581364  0.771285   
244128        3258    3.0     375.0  20.147  577.888  2.342504  0.830561   
244129        3259    4.0     375.0  19.055  577.668  3.026289  0.761552   
...            ...    ...       ...     ...      ...       ...       ...   
256489       15619  646.0     393.0  21.013  582.024       NaN       NaN   
256490       15620  647.0     393.0  20.718  582.152       NaN       NaN   
256491       15621  648.0     393.0  20.525  582.667       NaN       NaN   
256492       15622  649.0     393.0  20.849  582.501       NaN       NaN   
256493       15623  650.0     393.0  21.293  582.026       NaN       NaN   

        Quality  SN_Ratio  Mean_Intensity  
244125   11.389     0.969         314.008  
244126   10.487     1.024         310.550  
244127   11.502     1.076         317.744  
244128   10.844     0.997         312.070  
244129   12.443     0.970         313.426  
...         ...       ...             ...  
256489   17.759     0.793         303.101  
256490   16.935     0.794         302.760  
256491   17.470     0.808         304.992  
256492   16.701     0.831         302.574  
256493   16.707     0.899         304.496  

[3255 rows x 10 columns]

In [ ]:
out = features.calculate_features(df)

In [20]:
datai = out.copy()

In [18]:
data_process.bin_data(out)

Track_ID         alpha      D_fit  kurtosis  asymmetry1  asymmetry2  \
0         0.0  1.831263e+00   0.000241  1.997559    0.998218    0.021115   
1         1.0  1.033667e+00   0.008454  2.513723    0.794861    0.239445   
2         2.0  1.942682e-01   6.361014  2.202512    0.878785    0.179701   
3         3.0  1.320225e+00   0.000603  1.746784    0.907499    0.155759   
4         4.0  1.476719e-01   0.069698  2.098423    0.245925    0.580500   
..        ...           ...        ...       ...         ...         ...   
759     759.0  3.699544e-01   1.948400  3.372174    0.729852    0.280297   
760     760.0  8.310040e-01   6.481817  2.874905    0.623719    0.342737   
761     761.0  2.291954e-08  10.552383  2.524026    0.035870    0.825548   
762     762.0  3.212006e-01   2.628704  2.672722    0.989629    0.051053   
763     763.0  2.569500e+00   0.001470  3.653809    0.590768    0.361702   

     asymmetry3        AR  elongation  boundedness  ...  Std Mean_Intensity  \
0      0.615259  4.363174    0.770809     0.001011  ...                 NaN   
1      0.208585  2.598729    0.615196     0.054603  ...                 NaN   
2      0.276744  1.803189    0.445427     0.092150  ...                 NaN   
3      0.310321  2.233095    0.552191     0.004558  ...                 NaN   
4      0.035860  1.393029    0.282140     0.125951  ...                 NaN   
..          ...       ...         ...          ...  ...                 ...   
759    0.171975  1.226852    0.184906     0.114899  ...                 NaN   
760    0.127609  1.906663    0.475524     0.185571  ...                 NaN   
761    0.004576  1.244070    0.196186     0.119018  ...                 NaN   
762    0.523528  4.480281    0.776800     0.117893  ...                 NaN   
763    0.116380  1.654964    0.395757     0.112864  ...                 NaN   

     Mean SN_Ratio  Std SN_Ratio  Mean Deff1  Std Deff1  Mean Deff2  \
0         0.917897      0.090352    0.009648   0.004699    0.008130   
1         1.252501      0.233886    0.589796   0.455805    0.051851   
2         1.252501      0.233886    0.589796   0.455805    0.051851   
3         0.969071      0.171100    0.071380   0.076882    0.013941   
4         0.978499      0.158402    0.060243   0.094853    0.000427   
..             ...           ...         ...        ...         ...   
759       1.365326      0.060517    0.617007   0.429699    0.030214   
760       1.386207      0.068709    1.370460   0.904748    0.200053   
761       1.386207      0.068709    1.370460   0.904748    0.200053   
762       1.365326      0.060517    0.617007   0.429699    0.030214   
763       1.365326      0.060517    0.617007   0.429699    0.030214   

     Std Deff2  binx  biny  bins  
0     0.002738     3    12    60  
1     0.030837     2    15    47  
2     0.030837     2    15    47  
3     0.012579     0    14    14  
4     0.000004     0    15    15  
..         ...   ...   ...   ...  
759   0.029287    12     0   192  
760   0.000000    15     0   240  
761   0.000000    15     0   240  
762   0.029287    12     0   192  
763   0.029287    12     0   192  

[764 rows x 70 columns]

In [40]:
count = 0

for xrange in range(0, 16):
            for yrange in range(0, 16):
                bitesize = datai[(datai['X'] >= 128*xrange) & (datai['X'] < 128*(xrange+1)) &
                                 (datai['Y'] >= 128*yrange) & (datai['Y'] < 128*(yrange+1))]
                bitesize.replace([np.inf, -np.inf], np.nan)
                if bitesize.shape[0] >0:
                   count += 1
                print(bitesize.shape)
                print(bitesize['Track_ID'].unique())
                # for col in bitesize.columns:
                #     if col not in nonnum and 'Mean' not in col and 'Std' not in col:
                #         datai['Mean '+ col][bitesize.index] = np.nanmean(bitesize[col])
                #         datai['Std '+ col][bitesize.index] = np.nanstd(bitesize[col])

(0, 70)
[]
(0, 70)
[]
(3, 70)
[598. 600. 605.]
(3, 70)
[570. 597. 602.]
(5, 70)
[375. 385. 389. 391. 393.]
(2, 70)
[384. 388.]
(14, 70)
[370. 376. 377. 379. 380. 381. 382. 383. 386. 390. 392. 394. 395. 396.]
(0, 70)
[]
(3, 70)
[143. 151. 160.]
(3, 70)
[155. 168. 169.]
(2, 70)
[161. 171.]
(2, 70)
[163. 164.]
(0, 70)
[]
(0, 70)
[]
(10, 70)
[ 3. 22. 23. 27. 34. 38. 39. 42. 43. 45.]
(4, 70)
[ 4.  8. 13. 17.]
(0, 70)
[]
(6, 70)
[560. 567. 571. 574. 576. 579.]
(1, 70)
[582.]
(1, 70)
[563.]
(0, 70)
[]
(2, 70)
[374. 378.]
(0, 70)
[]
(0, 70)
[]
(4, 70)
[154. 156. 181. 185.]
(6, 70)
[148. 149. 152. 158. 159. 174.]
(2, 70)
[172. 173.]
(1, 70)
[146.]
(4, 70)
[ 6.  7.  9. 20.]
(0, 70)
[]
(0, 70)
[]
(3, 70)
[ 5. 32. 44.]
(1, 70)
[595.]
(2, 70)
[603. 607.]
(1, 70)
[609.]
(0, 70)
[]
(0, 70)
[]
(0, 70)
[]
(1, 70)
[387.]
(1, 70)
[373.]
(3, 70)
[162. 165. 170.]
(3, 70)
[145. 147. 178.]
(3, 70)
[153. 179. 183.]
(3, 70)
[150. 166. 167.]
(0, 70)
[]
(0, 70)
[]
(1, 70)
[35.]
(18, 70)
[ 1.  2. 10. 15. 18. 19. 

In [35]:
len(datai)

764

In [3]:
# To implement: visualizations of diffusion mode counts


In [ ]:
# to implement: visualizations of trajectory length for different diffusion modes, for each class